version: '3'
services:
  database:
    container_name: my_mysql
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - ./docker/data:/var/lib/mysql
    restart: always
    networks:
      - test_network

  application:
    container_name: my_app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:${MYSQL_DOCKER_PORT}/${MYSQL_DATABASE}?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      SPRING_APPLICATION_JSON: '{
#          "spring.datasource.url"  : "jdbc:mysql://database:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true",
#          "spring.datasource.username" : "root",
#          "spring.datasource.password" : "1234",
#          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
#          "spring.jpa.hibernate.ddl-auto" : "create"
#        }'
    restart: always
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network:
    driver: bridge

