version: '3'
services:
  database:
    container_name: my_mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=testdb
    ports:
      - 3306:3306
    volumes:
      - ./docker/data:/var/lib/mysql
    networks:
      - test_network

  application:
    container_name: my_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://my_mysql:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "1234",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "create"
        }'
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network:
    driver: bridge

